[build]
  publish = "static"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[redirects]]
  from = "/daisy"
  to = "/daisy-audio-reactive.html"
  status = 200
